### ISSUE TITLE
snackbarの表示について

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/2023-quaint-app#199]
エラーsnackbarなどは特に、残したままでいると、
関係ない正しく動いている部分でエラーしてるかのように誤解しやすいので
そういったことが起こりそうな場合(e.g.以前やったdialogを開くときに消すなど)をつぶしておきましょう
また、現在成功snackbarとエラーsnackbarの重ね掛けができるので
別にどっちでもいいですが、snackbar出すときもう片方を消すようにしましょう
そっちの方がスマートだと思われます

**Comment by ekkekuru2** [comment]
あとsnackbarが一番下の、ホームとか探すとか整理券の、appbarと被らないようにもしたいかも

**Comment by ekkekuru2** [comment]
あ、ごめん#198で言ってたね
