### ISSUE TITLE
もっと「祭徠」っぽさ？

### ISSUE THREAD

**Issue by ekkekuru2** [hibiya-itchief/2023-quaint-app#288]
なんか祭徠をもっと押し出した遊び心のあるデザインに？
タグを提灯ぽくしてみたり
団体のカードを屋台みたいに
紅白幕とか？

**Comment by hibiyahibiyahibiya** [comment]
マテリアルデザインからいい感じに抜け出したいですよね

**Comment by hibiyahibiyahibiya** [comment]
いまのmdi-hogehogeじゃなくてfont awesomeのアイコン使ったらよくなったりしますかね？
いちおうvuetifyの[v-icon](https://v2.vuetifyjs.com/ja/components/icons/#font-awesome)で使えるみたいなので

**Comment by ekkekuru2** [comment]
かわいい

**Comment by ekkekuru2** [comment]
出来れば星陵祭装飾チーフの人とかに一通りのアイコンセットデザインしてもらえたりしたら神なんだけどな

**Comment by hibiyahibiyahibiya** [comment]
それおもしろそうですね(咄嗟に作れないのは何点ですが)
ただ基本はmdiやfont-awesomeで、ちょっと微妙なアイコンだけ、あるいはアクセントをつけるために特注、ってやり方がよさそうでしょうか
