### ISSUE TITLE
トップページの背景画像

### ISSUE THREAD

**Issue by ekkekuru2** [hibiya-itchief/2023-quaint-app#323]
チーフ会の大きな装飾物が完成し始めているので、
今 @ItsukiKigoshi が作ってくださった各クラスのサムネをレイアウトした画像のところに、それを載せてスライドショーにするのはどうでしょう

**Comment by hibiyahibiyahibiya** [comment]
スライドショーって[これ](https://v2.vuetifyjs.com/ja/components/carousels/#cycle)のイメージですか？

**Comment by ekkekuru2** [comment]
related to #288

**Comment by hibiyahibiyahibiya** [comment]
これ実装試みたんですが、おそらく
・groupsをランダムでsortしたい(11R→38Rの順でcarouselsすると不平等だから)
・画像を上げていないgroupを飛ばす処理をつくらないといけない
と、ユーザーの負担および開発者の負担という理由でカットしたいです…いいでしょうか

**Comment by hibiyahibiyahibiya** [comment]
carouselsの実装自体はこんな感じで、あとheight/widthを調整します
```
    <v-carousel cycle hide-delimiters>
      <v-carousel-item
        v-for="group in groups"
        :key="group.id"
        :src="group.public_thumbnail_image_url"
        contain
      ></v-carousel-item>
    </v-carousel>
```
